<a href="https://colab.research.google.com/github/betsyninoska/Python/blob/master/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
###import pandas as pd
##import matplotlib.pyplot as plt
##import seaborn as sns



#Diferentes tipos de array
# Array de ceros
zeros = np.zeros(5)
print("Array de ceros:", zeros)

# Array de unos
unos = np.ones(3)
print("Array de unos:", unos)

# Array con un rango de valores
rango = np.arange(1, 11)
print("Array con rango:", rango)

# Array con valores espaciados linealmente
espaciado = np.linspace(0, 10, 5)
print("Array espaciado:", espaciado)

# Array con valores aleatorios entre 0 y 1
aleatorio = np.random.rand(4)
print("Array aleatorio:", aleatorio)

# Array con valores aleatorios enteros
enteros_aleatorios = np.random.randint(1, 10, size=3)
print("Array de enteros aleatorios:", enteros_aleatorios)



####




# Crear dos arrays de ejemplo
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])

# Suma elemento por elemento
suma = arr1 + arr2
print("Suma:", suma)

# Resta elemento por elemento
resta = arr1 - arr2
print("Resta:", resta)

# Multiplicación elemento por elemento
multiplicacion = arr1 * arr2
print("Multiplicación:", multiplicacion)

# División elemento por elemento
division = arr1 / arr2
print("División:", division)


#Manipulacion de array 3 x3



# Crear un array 3x3
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Acceder a elementos específicos
print("Elemento en la fila 1, columna 2:", arr[0, 1])  # Salida: 2

# Modificar un elemento
arr[1, 2] = 10
print("Array modificado:\n", arr)

# Slicing (extraer subconjuntos del array)
sub_array = arr[0:2, 1:]  # Filas 0 y 1, columnas desde la 1 en adelante
print("Sub-array:\n", sub_array)

# Operaciones matemáticas
suma_filas = np.sum(arr, axis=0)  # Suma de cada columna
print("Suma de filas:", suma_filas)

# Transponer el array
arr_transpuesto = arr.T
print("Array transpuesto:\n", arr_transpuesto)





In [ ]:
# prompt: manipular array 3 por 3

import numpy as np

# Crear un array 3x3
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Acceder a elementos específicos
print("Elemento en la fila 1, columna 2:", arr[0, 1])  # Salida: 2

# Modificar un elemento
arr[1, 2] = 10
print("Array modificado:\n", arr)

# Slicing (extraer subconjuntos del array)
sub_array = arr[0:2, 1:]  # Filas 0 y 1, columnas desde la 1 en adelante
print("Sub-array:\n", sub_array)

# Operaciones matemáticas
suma_filas = np.sum(arr, axis=0)  # Suma de cada columna
print("Suma de filas:", suma_filas)

# Transponer el array
arr_transpuesto = arr.T
print("Array transpuesto:\n", arr_transpuesto)


Elemento en la fila 1, columna 2: 2
Array modificado:
 [[ 1  2  3]
 [ 4  5 10]
 [ 7  8  9]]
Sub-array:
 [[ 2  3]
 [ 5 10]]
Suma de filas: [12 15 22]
Array transpuesto:
 [[ 1  4  7]
 [ 2  5  8]
 [ 3 10  9]]
